
spring:
  name: plazoleta
  jpa:

    generate-ddl: 'true'
    database: MYSQL
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: 'true'
    show-sql: 'true'
    hibernate:
      ddl-auto: update

  datasource:
    url: jdbc:mysql://localhost:3306/plazoleta
    username : root
    password: Pepita123.

server:
  port: 8282

twilio:
   account:
     sid: AC0db616a004744b5d4bd52b2d2e824118
   auth:
     token: 02ececab85c95ac32dfbebc843fc56a1